### ISSUE TITLE
Name for AppSync DataSource is invalid 

### ISSUE THREAD

**Issue by timo92** [Meterius/serverless-aws-auto-resource-names#1]
According to the [aws documentation](https://docs.aws.amazon.com/appsync/latest/APIReference/API_DataSource.html) the name fo a DataSource must match the pattern [_A-Za-z][_0-9A-Za-z]*. Currently names are generated with - (minus) characters which violates the pattern.

**Comment by Meterius** [comment]
Should be fixed by commit e1b5472 and is available with npm version ^0.2.3
